[package]
name = "Maestro"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
shlex = "1.3.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
maestro-core = { path = "../../maestro-core" }
inquire = "0.7.5"